version: 2

defaults: &defaults
  docker:
    - image: cimg/openjdk:11-jdk
  resource_class: medium
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx512m
    TERM: dumb

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https:/codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  test:
    <<: *defaults
    environment:
      JACOCO_SOURCE_PATH: ./src/main/java
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run:
          name: Run test and coverate report format
          command: |
            gradle :test
            ./tmp/cc-test-reporter format-coverage -t jacoco -o ./tmp/codeclimate.jacoco.json ./build/reports/jacoco/test/jacocoTestReport.xml
      - save_cache:
          paths:
            - .gradle
          key: java-v1-dependencies-{{ checksum "build.gradle.kts" }}
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.jacoco.json
  upload-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter upload-coverage -i ./tmp/codeclimate.jacoco.json

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload-coverage:
          requires:
            - test