version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "java-reactive-logger/build.gradle.kts" }}-{{ checksum "kotlin-coroutine-reactive-logger/build.gradle.kts" }}
            - v1-dependencies-
      - run: gradle :java-reactive-logger:test
      - run: gradle :kotlin-coroutine-reactive-logger:test
      - save_cache:
          paths:
            - ~/java-reactive-logger/.gradle
            - ~/kotlin-coroutine-reactive-logger/.gradle
          key: v1-dependencies-{{ checksum "java-reactive-logger/build.gradle.kts" }}-{{ checksum "kotlin-coroutine-reactive-logger/build.gradle.kts" }}
