version: 2

defaults: &defaults
  docker:
    - image: cimg/openjdk:11.0.16
  resource_class: medium
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx512m
    TERM: dumb

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https:/codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  test:
    <<: *defaults
    environment:
      JACOCO_SOURCE_PATH: ./reactive-logger/src/main/kotlin
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "reactive-logger/build.gradle.kts" }}
      - run:
          name: Run test and coverate report format
          command: |
            gradle :reactive-logger:test
            ./tmp/cc-test-reporter format-coverage -t jacoco -o ./tmp/codeclimate.jacoco.json ./reactive-logger/build/reports/jacoco/test/jacocoTestReport.xml
      - save_cache:
          paths:
            - ./reactive-logger/.gradle
          key: v1-dependencies-{{ checksum "reactive-logger/build.gradle.kts" }}
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.jacoco.json
  example-java-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "reactive-logger-example-java/build.gradle" }}
      - run:
          name: Run test
          command: |
            gradle :reactive-logger-example-java:test
      - save_cache:
          paths:
            - ./reactive-logger-example-java/.gradle
          key: v1-dependencies-{{ checksum "reactive-logger-example-java/build.gradle" }}
  example-kotlin-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "reactive-logger-example-kotlin/build.gradle.kts" }}
      - run:
          name: Run test
          command: |
            gradle :reactive-logger-example-kotlin:test
      - save_cache:
          paths:
            - ./reactive-logger-example-kotlin/.gradle
          key: v1-dependencies-{{ checksum "reactive-logger-example-kotlin/build.gradle.kts" }}
  upload-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter upload-coverage -i ./tmp/codeclimate.jacoco.json

workflows:
  version: 2
  commit:
    jobs:
      - build
      - example-java-test
      - example-kotlin-test
      - test:
          requires:
            - build
      - upload-coverage:
          requires:
            - test