reactive-logger:
  instances:
    example-instance:
      logger: io.github.numichi.reactive.logger.example.controllers.ReactiveLoggerController
      context-key: "context-key-from-yml"
      scheduler: bounded_elastic
    another-example-instance:
      context-key: "another-context-key-from-yml"
      scheduler: parallel
